"""
CAG Estimate Chat Interface

- Chat with message history kept in ``st.session_state`` and re-rendered on every rerun.
- Two modes: streaming markdown (token by token) and structured JSON (task table).
- Friendly guardrail messages; raw server errors are never displayed.

Note: the backend is single-shot per message. Every request is estimated on its
own; the history is a UI convenience and is NOT sent back as conversation context.
"""

import html as html_lib
import re
from datetime import datetime
from typing import Any

import estimate_client
import streamlit as st
import view_models

MODE_STREAMING = "Streaming (markdown)"
MODE_STRUCTURED = "Structured (JSON)"
DEFAULT_HOURLY_RATE = 40
TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"

st.set_page_config(
    page_title="CAG Estimate Chat",
    page_icon="💬",
    layout="wide",
    initial_sidebar_state="expanded",
)


def session_defaults() -> dict[str, Any]:
    return {
        "messages": [],
        "call_count": 0,
        "total_tokens": 0,
        "session_cost": 0.0,
        "last_call": None,
    }


def init_session_state() -> None:
    """Initialize session state variables."""
    for key, value in session_defaults().items():
        st.session_state.setdefault(key, value)


def now() -> str:
    return datetime.now().astimezone().strftime(TIMESTAMP_FORMAT)


def markdown_to_bubble_html(text: str) -> str:
    """
    Escape user/LLM text for safe HTML embedding, then convert the small
    subset of Markdown we actually produce (bold, bullet lines, newlines)
    into HTML so it renders correctly inside a custom bubble <div> — plain
    st.markdown() would otherwise treat that div as a raw HTML block and
    skip Markdown processing of its contents entirely.
    """
    escaped = html_lib.escape(text)
    escaped = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", escaped)
    escaped = re.sub(r"(?m)^- (.+)$", r"&nbsp;&nbsp;• \1", escaped)
    escaped = escaped.replace("\n", "<br>")
    return escaped


def render_message_html(role: str, text: str, timestamp: str = "", streaming: bool = False) -> str:
    """Render a message as a WhatsApp/iMessage-style chat bubble: user on the
    right in sky blue, assistant on the left in neutral gray."""
    content_html = markdown_to_bubble_html(text)
    cursor = " ▌" if streaming else ""
    timestamp_html = (
        f'<div style="font-size:0.7rem; opacity:0.7; margin-top:6px; '
        f'text-align:{"right" if role == "user" else "left"};">{timestamp}</div>'
        if timestamp else ""
    )

    if role == "user":
        justify, radius, bg, color = "flex-end", "18px 18px 4px 18px", "#87CEEB", "#08303f"
    else:
        justify, radius, bg, color = "flex-start", "18px 18px 18px 4px", "#F0F2F6", "#1a1a1a"

    return f"""
    <div style="display:flex; justify-content:{justify}; margin:10px 0;">
      <div style="background-color:{bg}; color:{color}; padding:10px 16px;
                  border-radius:{radius}; max-width:75%; line-height:1.5;
                  box-shadow:0 1px 2px rgba(0,0,0,0.12); word-wrap:break-word;">
        {content_html}{cursor}
        {timestamp_html}
      </div>
    </div>
    """


THINKING_BUBBLE_HTML = """
<div style="display:flex; justify-content:flex-start; margin:10px 0;">
  <div style="background-color:#F0F2F6; padding:10px 16px; border-radius:18px 18px 18px 4px;
              box-shadow:0 1px 2px rgba(0,0,0,0.12);">
    <div class="thinking-indicator">
      <span>🤖 Thinking</span>
      <span class="thinking-dot"></span>
    </div>
  </div>
</div>
<style>
.thinking-indicator { display: flex; align-items: center; gap: 10px; color: #666; }
.thinking-dot {
  position: relative;
  width: 6px; height: 6px; border-radius: 50%;
  background-color: #9880ff;
  animation: thinking-blink 1s infinite linear alternate;
  animation-delay: .5s;
}
.thinking-dot::before, .thinking-dot::after {
  content: ''; position: absolute; top: 0;
  width: 6px; height: 6px; border-radius: 50%;
  background-color: #9880ff;
}
.thinking-dot::before { left: -12px; animation: thinking-blink 1s infinite linear alternate; animation-delay: 0s; }
.thinking-dot::after { left: 12px; animation: thinking-blink 1s infinite linear alternate; animation-delay: 1s; }
@keyframes thinking-blink {
  0% { background-color: #9880ff; }
  50%, 100% { background-color: rgba(152, 128, 255, 0.2); }
}
</style>
"""


def render_structured(result: dict[str, Any], cached: bool) -> None:
    """Render a ProjectEstimation dict: cache badge, summary, task table and totals."""
    with st.chat_message("assistant"):
        if cached:
            st.success("⚡ Served from cache")
        else:
            st.info("🧠 Freshly generated by the model")
        st.subheader(result["project_name"])
        st.write(result["meeting_summary"])
        st.dataframe(view_models.task_rows(result), hide_index=True)
        for column, (label, value) in zip(
            st.columns(5), view_models.totals(result).items(), strict=True
        ):
            column.metric(label, value)
        assumptions = result["summary"].get("assumptions") or []
        if assumptions:
            st.markdown("**Assumptions**\n" + "\n".join(f"- {a}" for a in assumptions))


def render_message(message: dict[str, Any]) -> None:
    """Render one stored message according to its kind."""
    kind = message.get("kind", "text")
    if kind == "structured":
        render_structured(message["result"], message["cached"])
    elif kind == "error":
        st.error(message["content"])
    else:
        st.markdown(
            render_message_html(message["role"], message["content"], message.get("timestamp", "")),
            unsafe_allow_html=True,
        )


def store_message(role: str, **fields: Any) -> None:
    st.session_state.messages.append({"role": role, "timestamp": now(), **fields})


def extract_usage(final_event: dict[str, Any]) -> tuple[dict[str, Any], float]:
    """Token usage dict and total cost (USD) from a ``done`` event."""
    tokens = final_event.get("tokens_used", {})
    cost = final_event.get("cost_breakdown", {}).get("total_cost_usd", 0)
    return tokens, cost


def record_usage(final_event: dict[str, Any]) -> None:
    tokens, cost = extract_usage(final_event)
    st.session_state.call_count += 1
    st.session_state.total_tokens += tokens.get("total_tokens", 0)
    st.session_state.session_cost += cost
    st.session_state.last_call = {
        "model_name": final_event.get("model", "N/A"),
        "provider": final_event.get("provider", "N/A"),
        "input_tokens": tokens.get("input_tokens", 0),
        "output_tokens": tokens.get("output_tokens", 0),
        "cost_usd": cost,
        "finish_reason": final_event.get("finish_reason", "stop"),
    }


def consume_stream(prompt: str, placeholder: Any) -> tuple[str, dict[str, Any] | None, str | None]:
    """Render tokens live; return (text, done event, safe error message)."""
    full_text, final_event, error = "", None, None
    for event in estimate_client.stream_events(prompt, DEFAULT_HOURLY_RATE):
        if event["type"] == "token":
            full_text += event.get("content", "")
            placeholder.markdown(
                render_message_html("assistant", full_text, streaming=True),
                unsafe_allow_html=True,
            )
        elif event["type"] == "done":
            final_event = event
        elif event["type"] == "error":
            error = event["message"]
    return full_text, final_event, error


def metrics_footer(final_event: dict[str, Any]) -> str:
    tokens, cost = extract_usage(final_event)
    return f"\n\n---\n**API Metrics:** {tokens.get('total_tokens', 0):,} tokens · ${cost:.6f}"


def run_streaming(prompt: str) -> None:
    """Stream the markdown answer live, then store it (or the safe error)."""
    placeholder = st.empty()
    placeholder.markdown(THINKING_BUBBLE_HTML, unsafe_allow_html=True)
    full_text, final_event, error = consume_stream(prompt, placeholder)
    placeholder.empty()
    if error or not (final_event and full_text):
        error = error or view_models.GENERIC_ERROR
        store_message("assistant", kind="error", content=error)
        st.error(error)
        return
    store_message("assistant", kind="text", content=full_text + metrics_footer(final_event))
    render_message(st.session_state.messages[-1])
    record_usage(final_event)


def run_structured(prompt: str) -> None:
    """Call the structured endpoint and store the table-ready answer (or the safe error)."""
    with st.spinner("Estimating..."):
        answer = estimate_client.fetch_structured(prompt, DEFAULT_HOURLY_RATE)
    if answer.result is None:
        store_message("assistant", kind="error", content=answer.error)
        st.error(answer.error)
        return
    store_message("assistant", kind="structured", result=answer.result, cached=answer.cached)
    render_message(st.session_state.messages[-1])
    st.session_state.call_count += 1


def handle_prompt(prompt: str, mode: str) -> None:
    store_message("user", kind="text", content=prompt)
    render_message(st.session_state.messages[-1])
    if not estimate_client.check_api_health():
        message = "⚠️ API is not running. Start it with: `docker-compose up`"
        store_message("assistant", kind="error", content=message)
        st.error(message)
    elif mode == MODE_STRUCTURED:
        run_structured(prompt)
    else:
        run_streaming(prompt)


def render_mode_switch() -> str:
    with st.sidebar:
        st.header("⚙️ Controls & Info")
        return st.radio("Response mode", [MODE_STREAMING, MODE_STRUCTURED])


def reset_conversation() -> None:
    for key, value in session_defaults().items():
        st.session_state[key] = value


def render_last_call(last: dict[str, Any]) -> None:
    with st.expander("📋 Last Call Info", expanded=False):
        col1, col2 = st.columns(2)
        with col1:
            st.metric("Model", last["model_name"])
            st.metric("Input Tokens", f"{last['input_tokens']:,}")
        with col2:
            st.metric("Output Tokens", f"{last['output_tokens']:,}")
            st.metric("Cost", f"${last['cost_usd']:.6f}")
        st.caption(f"Provider: {last['provider']} · Finish reason: {last['finish_reason']}")


def render_sidebar_info() -> None:
    with st.sidebar:
        if st.button("🔄 New Chat", use_container_width=True, help="Start a fresh conversation"):
            reset_conversation()
            st.rerun()
        st.divider()
        messages = st.session_state.messages
        st.info(
            "**Conversation Stats:**\n"
            f"- 👤 Your messages: {sum(m['role'] == 'user' for m in messages)}\n"
            f"- 🤖 Assistant messages: {sum(m['role'] == 'assistant' for m in messages)}"
        )
        st.subheader("📊 Session Metrics")
        healthy = estimate_client.check_api_health()
        st.caption(f"{'🟢' if healthy else '🔴'} API: {'Connected' if healthy else 'Disconnected'}")
        col1, col2 = st.columns(2)
        col1.metric("Calls Made", st.session_state.call_count)
        col1.metric("Total Tokens", st.session_state.total_tokens)
        col2.metric("Session Cost", f"${st.session_state.session_cost:.6f}")
        if st.session_state.last_call:
            render_last_call(st.session_state.last_call)
        st.divider()
        st.caption(
            "Each message is estimated on its own: the backend is single-shot and does "
            "not use earlier messages as context."
        )


def main() -> None:
    init_session_state()
    mode = render_mode_switch()
    st.title("💬 Ready to estimate your projects?")
    st.markdown("**Your AI assistant, expert in software project estimation**")
    st.divider()
    if not st.session_state.messages:
        st.info("👋 Start a conversation by describing your project below!")
    for message in st.session_state.messages:
        render_message(message)
    prompt = st.chat_input(
        placeholder="Describe your project... (you can paste a meeting transcription)"
    )
    if prompt:
        handle_prompt(prompt, mode)
    render_sidebar_info()


main()
