[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "error"

[server]
maxUploadSize = 200
enableXsrfProtection = true
